
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    env_file:
      - .env
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9200:9200"
    networks:
      - musicxmlnet
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    container_name: kibana
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_NODE}
      - ELASTICSEARCH_USERNAME=${APP_ES_USERNAME}
      - ELASTICSEARCH_PASSWORD=${APP_ES_PASSWORD}
      - SERVER_PUBLICBASEURL=${KIBANA_NODE}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - musicxmlnet

  webapp:
    build: ./webapp
    env_file:
      - .env
    container_name: webapp
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_NODE}
      - ELASTICSEARCH_USERNAME=${APP_ES_USERNAME}
      - ELASTICSEARCH_PASSWORD=${APP_ES_PASSWORD}
    depends_on:
    - elasticsearch
    networks:
      - musicxmlnet

networks:
  musicxmlnet:
    external: true


volumes:
  esdata:

