version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      # A minimal single-node configuration for testing
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch

volumes:
  esdata:
